In [2]:
import gensim.downloader as api
model = api.load("word2vec-google-news-300")

In [3]:
word_vector = model
print(word_vector['Man'])
print(word_vector['cat'].shape)

[ 1.03515625e-01  8.98437500e-02 -4.78515625e-02  2.24609375e-02
  2.13867188e-01 -4.27246094e-02 -2.41210938e-01  1.62109375e-01
  3.63281250e-01 -1.13281250e-01 -1.99218750e-01  3.61328125e-02
 -8.49609375e-02 -9.22851562e-02 -5.76171875e-02 -2.95410156e-02
 -2.27539062e-01 -1.59179688e-01 -7.03125000e-02 -1.41601562e-01
  6.07299805e-03 -1.66015625e-01  1.73828125e-01  4.10156250e-02
 -1.01074219e-01 -1.87500000e-01 -1.04003906e-01  2.59765625e-01
  3.45703125e-01  6.20117188e-02 -1.14746094e-01  1.02539062e-01
 -9.47265625e-02 -1.45507812e-01 -2.63671875e-01  2.45117188e-01
  8.30078125e-02 -1.07910156e-01  1.21582031e-01  1.60156250e-01
  1.14257812e-01 -1.89453125e-01  2.83203125e-01  7.86132812e-02
 -6.12792969e-02 -3.14453125e-01 -9.03320312e-03  6.68945312e-02
  7.76367188e-02 -5.90820312e-02 -4.47265625e-01  2.48046875e-01
  6.64062500e-02 -5.15136719e-02  9.22851562e-02 -3.32031250e-02
  1.06933594e-01 -1.01562500e-01  2.59765625e-01 -6.64062500e-02
  1.76757812e-01  2.71484

In [4]:
print(word_vector.most_similar(positive=['King','Woman'], negative=['Man'],topn=10))

[('Queen', 0.4929387867450714), ('Tupou_V.', 0.45174285769462585), ('Oprah_BFF_Gayle', 0.4422132968902588), ('Jackson', 0.440250426530838), ('NECN_Alison', 0.4331282675266266), ('Whitfield', 0.42834725975990295), ('Ida_Vandross', 0.42084527015686035), ('prosecutor_Dan_Satterberg', 0.420758992433548), ('martin_Luther_King', 0.42059651017189026), ('Coretta_King', 0.4202733635902405)]


In [5]:
print(word_vector.most_similar('tower',topn=5))

[('towers', 0.8531750440597534), ('skyscraper', 0.6417425870895386), ('Tower', 0.639177143573761), ('spire', 0.594687819480896), ('responded_Understood_Atlasjet', 0.5931612253189087)]


In [12]:
print(word_vector.similarity('man','woman'))
print(word_vector.similarity('man','king'))
print(word_vector.similarity('rock','paper'))
print(word_vector.similarity('fool','woman'))

0.76640123
0.22942673
0.080210164
0.123176254


## creating vector embedding 

In [13]:
import torch
input_ids = torch.tensor([1,3,5,2])

vocab_size =6
output_dim = 3
torch.manual_seed(123)
embedding_layer=  torch.nn.Embedding(vocab_size,output_dim)

In [14]:
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


In [15]:
print(embedding_layer(torch.tensor([3])))

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [16]:
print(embedding_layer(input_ids))

tensor([[ 0.9178,  1.5810,  1.3010],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 1.2753, -0.2010, -0.1606]], grad_fn=<EmbeddingBackward0>)
